[[permission]]
identifier = "app-commands"
description = "Allows all custom commands"
commands.allow = [
    "search_aur",
    "get_packages_by_names",
    "get_chaotic_package_info",
    "get_chaotic_packages_batch",
    "get_metadata",
    "get_category_packages_paginated",
    "search_packages",
    "get_app_rating",
    "get_app_reviews",
    "get_chaotic_packages",
    "get_trending",
    "get_infra_stats",
    "fetch_repo",
    "get_package_variants",
    "trigger_repo_sync",
    "toggle_repo",
    "set_aur_enabled",
    "is_aur_enabled",
    "get_repo_states",
    "install_package",
    "check_installed_status",
    "uninstall_package",
    "get_system_info",
    "submit_review",
    "get_local_reviews",
    "get_repo_counts",
    "optimize_system",
    "toggle_repo_family",
    "clear_cache",
    "get_installed_packages",
    "check_for_updates",
    "get_package_icon",
    "launch_app",
    "perform_system_update",
    "fetch_pkgbuild",
    "get_orphans",
    "remove_orphans",
    "check_repo_status",
    "enable_repo",
    "reset_pacman_conf",
    "enable_repos_batch",
    "bootstrap_system",
    "repair_unlock_pacman",
    "repair_reset_keyring",
    "repair_emergency_sync",
    "check_pacman_lock",
    "set_one_click_control",
    "is_one_click_enabled",
    "set_one_click_enabled",
    "check_security_policy",
    "install_monarch_policy",
    "check_repo_sync_status",
    "check_app_update",
    "get_metadata_batch",
    "abort_installation",
    "update_and_install_package",
    "check_system_health",
    "set_repo_priority",
    "initialize_system",
    "check_initialization_status",
    "is_telemetry_enabled",
    "set_telemetry_enabled",
    "is_sync_on_startup_enabled",
    "set_sync_on_startup_enabled",
    "check_and_clear_refresh_requested",
    "get_all_installed_names",
    "get_install_mode_command",
    "track_event",
    "check_reboot_required",
    "get_pacnew_warnings",
    "fix_keyring_issues",
    "fix_keyring_issues_alias",
    "get_app_ratings_batch",
    "check_keyring_health",
    "get_distro_context"
]
