[[permission]]
identifier = "app-commands"
description = "Allows all custom commands"
commands.allow = [
    "search_aur",
    "get_packages_by_names",
    "get_chaotic_package_info",
    "get_chaotic_packages_batch",
    "get_metadata",
    "get_category_packages_paginated",
    "search_packages",
    "get_app_rating",
    "get_app_reviews",
    "get_metadata_batch",
    "abort_installation",
    "check_updates",
    "apply_updates",
    "perform_system_update",
    "get_system_update_command",
    "check_app_update",
    "check_installed_status",
    "install_package",
    "uninstall_package",
    "update_and_install_package",
    "check_system_health",
    "set_repo_priority",
    "check_initialization_status",
    "clear_sync_db_health_cache",
    "get_last_sync_age_seconds",
    "is_telemetry_enabled",
    "set_telemetry_enabled",
    "is_sync_on_startup_enabled",
    "set_sync_on_startup_enabled",
    "check_and_clear_refresh_requested",
    "get_all_installed_names",
    "get_install_mode_command",
    "track_event",
    "check_reboot_required",
    "get_pacnew_warnings",
    "fix_keyring_issues",
    "fix_keyring_issues_alias",
    "get_app_ratings_batch",
    "check_keyring_health",
    "get_distro_context",
    "get_cache_size",
    "get_orphans_with_size",
    "set_parallel_downloads",
    "get_mirror_rank_tool",
    "rank_mirrors",
    "test_mirrors",
    "force_refresh_databases",
    "sync_system_databases",
    "apply_os_config",
    "emit_sync_progress"
]
