[[permission]]
identifier = "app-commands"
description = "Allows all custom commands"
commands.allow = [
    "abort_installation",
    "apply_os_config",
    "apply_updates",
    "cancel_install",
    "check_and_clear_refresh_requested",
    "check_app_update",
    "check_initialization_status",
    "check_installed_status",
    "check_keyring_health",
    "check_pacman_lock",
    "check_reboot_required",
    "check_repo_sync_status",
    "check_security_policy",
    "check_system_health",
    "check_updates",
    "clear_build_cache",
    "clear_cache",
    "clear_pacman_package_cache",
    "clear_sync_db_health_cache",
    "emit_sync_progress",
    "fetch_pkgbuild",
    "fix_keyring_issues",
    "fix_keyring_issues_alias",
    "force_refresh_databases",
    "get_all_installed_names",
    "get_app_rating",
    "get_app_ratings_batch",
    "get_app_reviews",
    "get_cache_size",
    "get_category_packages_paginated",
    "get_chaotic_package_info",
    "get_chaotic_packages_batch",
    "get_distro_context",
    "get_essentials_list",
    "get_infra_stats",
    "get_installed_packages",
    "get_install_mode_command",
    "get_last_sync_age_seconds",
    "get_local_reviews",
    "get_metadata",
    "get_metadata_batch",
    "get_mirror_rank_tool",
    "get_orphans",
    "get_orphans_with_size",
    "get_package_icon",
    "get_packages_by_names",
    "get_package_variants",
    "get_pacnew_warnings",
    "get_repo_counts",
    "get_repo_states",
    "get_system_info",
    "get_system_update_command",
    "get_trending",
    "install_monarch_policy",
    "install_package",
    "is_advanced_mode",
    "is_aur_enabled",
    "is_notifications_enabled",
    "is_one_click_enabled",
    "is_sync_on_startup_enabled",
    "is_telemetry_enabled",
    "launch_app",
    "needs_startup_unlock",
    "optimize_system",
    "perform_system_update",
    "rank_mirrors",
    "remove_orphans",
    "repair_emergency_sync",
    "repair_reset_keyring",
    "repair_unlock_pacman",
    "search_aur",
    "search_packages",
    "set_advanced_mode",
    "set_aur_enabled",
    "set_notifications_enabled",
    "set_one_click_enabled",
    "set_parallel_downloads",
    "set_sync_on_startup_enabled",
    "set_telemetry_enabled",
    "submit_review",
    "sync_system_databases",
    "test_mirrors",
    "toggle_repo",
    "toggle_repo_family",
    "track_event",
    "trigger_repo_sync",
    "uninstall_package",
    "unlock_pacman_if_stale",
    "update_and_install_package"
]
